- name: Inicia Instancia Autonomous Database 
  hosts: localhost
  connection: local

  vars_files: vault.yaml


  tasks:
    - block:
        - name: Lista Todas las Instancias de ADB
          oracle.oci.oci_database_autonomous_database_facts:
             compartment_id: "{{ compartment_ocid }}"
             display_name: "{{ display_name }}"
          register: resultado

        - name: Valida si Existe Instancia
          assert:
             that:
                - resultado.autonomous_databases[0].display_name == display_name

        - set_fact:
             autonomous_database_id: "{{ resultado.autonomous_databases[0].id }}"

        - name: Inicia ADB
          oracle.oci.oci_database_autonomous_database_actions:
             autonomous_database_id: "{{ autonomous_database_id }}"
             action: 'start'
          register: result

        - name: Valida que la Instancia Inicio
          assert:
             that:
      rescue:

        - fail:
            msg: "ERROR, No se Logro Iniciar Instancia ADB."
